
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j.bulkhead:
  instances:
    weaponService:
      maxWaitDuration: 100ms
      maxConcurrentCalls: 1

resilience4j.thread-pool-bulkhead:
  instances:
    weaponService:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1

#resilience4j:
#  bulkhead:
#    weaponService:
#      maxWaitDuration: 100ms
#      maxConcurrentCalls: 1

#resilience4j:
#  circuitbreaker:
#    instances:
#      weaponService:
#        registerHealthIndicator: true
#        eventConsumerBufferSize: 10
#        failureRateThreshold: 50
#        minimumNumberOfCalls: 10
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        waitDurationInOpenState: 30s
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowSize: 10
#        slidingWindowType: COUNT_BASED
#        recordExceptions:
#          - org.springframework.web.reactive.function.client.WebClientRequestException
#  retry:
#    instances:
#      weaponService:
#        maxRetryAttempts: 3
#        waitDuration: 5s


